trend_analysis:
  description: >
    Analyze current social media trends to identify topics relevant to our brand.
  expected_output: >
    A list of 5 trending topics with brief descriptions.
  agent: researcher

content_creation:
  description: >
    Develop engaging posts based on the identified trends.
  expected_output: >
    5 social media posts tailored to our audience.
  agent: writer

content_review:
  description: >
    Review and refine the posts for clarity, tone, and scheduling.
  expected_output: >
    Finalized posts ready for publication with suggested posting times.
  agent: editor
  output_file: finalized_posts.md

